---
apiVersion: kubeflow.org/v1alpha3
kind: Experiment
metadata:
  name: bank-churner3
  namespace: demo01
spec:
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: accuracy
  algorithm:
    algorithmName: bayesianoptimization
  metricsCollectorSpec:
    kind: StdOut
  parameters:
    - name: n_estimators
      parameterType: categorical
      feasibleSpace:
        list:
          - 50
          - 100
    - name: learning_rate
      parameterType: categorical
      feasibleSpace:
        list:
          - 0.01
          - 0.1
    - name: max_depth
      parameterType: int
      feasibleSpace:
        min: "1"
        max: "2"
    - name: reg_lambda
      parameterType: int
      feasibleSpace:
        min: "1"
        max: "2"
    - name: od_wait
      parameterType: categorical
      feasibleSpace:
        list:
          - 50
          - 100
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: nEstimators
        description: N estimators for the model
        reference: n_estimators
      - name: learningRate
        description: Learning rate for the model
        reference: learning_rate
      - name: maxDepth
        description: Max depth for the model
        reference: max_depth
      - name: regLambda
        description: Reg lambda for the model
        reference: reg_lambda
      - name: odWait
        description: OD wait for the model
        reference: od_wait
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            containers:
              - name: training-container
                image: "docker.io/dampolo/bank-churner:newest3"
                command:
                  - python3
                  - -u
                  - /bank-churners.py
                args:
                  - "--n_estimators=${trialParameters.nEstimators}"
                  - "--learning_rate=${trialParameters.learningRate}"
                  - "--max_depth=${trialParameters.maxDepth}"
                  - "--reg_lambda=${trialParameters.regLambda}"
                  - "--od_wait=${trialParameters.odWait}"
            restartPolicy: Never