apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: "churn"
  namespace: demo01 # your-user-namespace
spec:
  cleanPodPolicy: None
  tfReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - name: tensorflow
            # modify this property if you would like to use a custom image
            image: mavencodev/tf_jobtitanic:1.0
            command:
                - "python"
                - "/tfjobtitan.py"
                - "--batch_size=10"
                - "--learning_rate=0.001"
                - "--optimizer=sgd"